### ISSUE TITLE
Kod düzenlemeleri

### ISSUE THREAD

**Issue by uyar** [dilanuslan/beets#1]
Merhaba,

Projenizi bitirme ödevi olarak sunmadan önce yapmanız gereken bazı düzenlemeler var:

1. Eklentinizin adını düzeltin, graduatorPlug olmaz. Yaptığı işle ilgili bir isim verin.
2. Yüzlerce satırlık tek bir kaynak kodu dosyası olmaz, uygun şekilde farklı dosyalara bölün.
3. Python2 sentaksı kullandığınız yerler var. "from future import division" veya object sınıfından türetme gibi. Python2 artık yok, kodu düzgün Python3 haline getirin.

Bitirme kitapçığıyla ilgili birkaç bir şey daha söyleyeceğim sonra.
İyi çalışmalar

**Comment by dilanuslan** [comment]
Merhaba hocam,

Belirttiğiniz değişiklikleri yapmaya çalıştım, final raporunda da bu değişiklikleri yapıp en kısa zamanda size göndereceğim. Gözümden kaçan bir nokta varsa tekrar geri dönüşünüzü almak isterim. Teşekkür ederim.

İyi haftasonları dilerim.
